CSLandscape/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('register.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

register/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
]

website/urls.py
from django.urls import path, re_path, include
from . import views
from django.views.static import serve
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin


from .views import ServiceDetailView

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name='about_us'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('blog/', views.blog, name='blog'),
    path('service_list/', views.ServiceListView.as_view(), name='service_list'),
    path('service_detail/<int:pk>', views.ServiceDetailView.as_view(), name='service_detail'),
    path('service/create/', views.ServiceCreate.as_view(), name='service_create'),
    path('invoice/create', views.InvoiceCreate.as_view(), name='invoice_create'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('accounts/', include('django.contrib.auth.urls')),
    path('service/<int:pk>/', ServiceDetailView.as_view(), name='service_detail'),
    path('accounts/logged', include('django.contrib.auth.urls')),
    path('review/create/', views.ReviewCreate.as_view(), name='review_create'),
    path('blog/', views.blog, name='blog'),
    path('blog/create/', views.BlogCreateView.as_view(), name='blog_create'),  # URL for creating new blog posts
]

register/models.py
from django.db import models

# Create your models here.

website/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Customer Reviews model
class Review(models.Model):
    review_id = models.CharField(max_length=50)
    review_rating = models.IntegerField()
    review_comments = models.CharField(max_length=500)
    review_image = models.ImageField(upload_to='review_images/', null=True, blank=True)
    service_id = models.ForeignKey('Service', on_delete=models.RESTRICT, null=True)


# Services that are offered
class Service(models.Model):
    service_id = models.CharField(max_length=50)
    service_title = models.CharField(max_length=200)
    service_info = models.CharField(max_length=200)
    service_cost = models.CharField(max_length=200)
    service_img = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.service_title

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('service_detail', args=[str(self.id)])


class ServiceRequest(models.Model):
    contact_ID = models.CharField(max_length=50)
    contact_first_name = models.CharField(max_length=200)
    contact_last_name = models.CharField(max_length=200)
    contact_preferredService = models.CharField(max_length=200)
    usr_id = models.ForeignKey(User, on_delete=models.RESTRICT, null=True)


# Invoice model
class Invoice(models.Model):
    invoice_no = models.CharField(max_length=50)
    invoice_date = models.CharField(max_length=200)
    invoice_total = models.CharField(max_length=200)
    invoice_description = models.CharField(max_length=200)
    service_id = models.ForeignKey('Service', on_delete=models.RESTRICT, null=True)


class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    publish_date = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(upload_to='blog_photos/', null=True, blank=True)

    def __str__(self):
        return self.title

register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username","first_name", "last_name", "email", "password1", "password2"]

register/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth.models import User, Group
from django.core.mail import send_mail
from django.conf import settings


# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            uname = form.cleaned_data['username']
            form.save()
            # get the new user info and set the group for this user to LibraryMember
            user = User.objects.get(username=uname)
            cust_group = Group.objects.get(name='Customer')
            user.groups.add(cust_group)
            user.save()
            subject = 'Welcome to CS Landscape'
            message = f'Hi {user.username}, thanks for registering for CS Landscape.'
            user_email = user.email
            send_mail(subject, message, 'nixiewander@gmail.com', [user_email])
            return redirect("login")

        return redirect("index")
    else:
        form = RegisterForm()

    return render(request, "register.html", {"form": form})

website/views.py
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from django.views.generic import CreateView
from website.models import Service, Review, ServiceRequest, Invoice, BlogPost
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import send_mail


# Create your views here.

def index(request):
    num_services = Service.objects.all().count()
    reviews = Review.objects.all().order_by('-review_id')[:5]  # Limiting to 5 reviews for example

    context = {
        'num_services': num_services,
        'reviews': reviews,  # Include reviews in the context
    }
    return render(request, 'index.html', context=context)


def about_us(request):
    num_services = Service.objects.all().count()
    context = {
        'num_services': num_services
    }
    return render(request, 'about_us.html', context=context)


def contact_us(request):
    num_services = Service.objects.all().count()
    context = {
        'num_services': num_services
    }
    return render(request, 'contact.html', context=context)


class ServiceListView(generic.ListView):
    model = Service


class ServiceDetailView(generic.DetailView):
    model = Service


class ServiceCreate(CreateView):
    model = Service
    fields = ['service_id', 'service_title', 'service_info', 'service_cost', 'service_img']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.save()
        return HttpResponseRedirect(reverse('service_list'))


class ReviewCreate(CreateView):
    model = Review
    fields = ['review_rating', 'review_comments', 'service_id']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.save()
        return HttpResponseRedirect(reverse('index'))


class InvoiceCreate(CreateView):
    model = Invoice
    fields = ['invoice_no', 'invoice_date', 'invoice_total', 'invoice_description', 'service_id']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.save()
        return HttpResponseRedirect(reverse('index'))


class BlogCreateView(LoginRequiredMixin, generic.CreateView):
    model = BlogPost
    fields = ['title', 'content']
    template_name = 'blog_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        super().form_valid(form)
        return HttpResponseRedirect(reverse('index'))

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)


def blog(request):
    # Update this view to pass blog posts to the template
    num_services = Service.objects.all().count()
    blog_posts = BlogPost.objects.all().order_by('-publish_date')
    context = {
        'num_services': num_services,
        'blog_posts': blog_posts,
    }
    return render(request, 'blog.html', context=context)

register/templates/register.html
<html lang="en">
{% extends "website/base.html" %}

{% block title %}Create an Account{% endblock %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
    <form method="POST" class="form-group">
   {% csrf_token %}

   {{ form|crispy }}
   <button type="submit" class="btn btn-success">Register</button>

    </form>

    <p><strong>Already have an account?</strong>
          <a href="{% url 'login' %}"> Login Now</a>
    </p>
{% endblock %}

</html>

website/templates/about_us.html
{% extends 'website/base.html' %}
{% load static %}

{% block content %}
    <!-- Outer Rectangle Background -->
    <div style="background-image: url('{% static 'images/image-5.jpg' %}'); background-size: cover; background-position: center; padding: 100px 0; text-align: center; position: relative;">

        <!-- Glossy Rectangle -->
        <div style="width: 60%; margin: 0 auto; background: rgba(255, 255, 255, 0.8); padding: 20px; border-radius: 8px; box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2); position: relative; overflow: hidden;">
            <!-- Gloss Effect Overlay -->
            <div style="position: absolute; top: -50%; right: -50%; bottom: -50%; left: -50%; background: linear-gradient(45deg, rgba(255, 255, 255, 0.4), transparent); transform: rotate(30deg);"></div>

            <!-- About Us Text Content -->
            <div style="position: relative; z-index: 1;">
                <h1>About Us</h1>
                <p>Welcome to CS Landscaping, where your outdoor dreams come to life!</p>
                <!-- Additional paragraphs and content here -->
            </div>
        </div>
    </div>

    <!-- History and Values Section -->
    <div style="display: flex; justify-content: space-between; align-items: flex-start; padding: 20px;">
        <div style="flex: 1; padding-right: 10px;">
            <h2>Our History</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum. Donec in efficitur lectus.</p>
        </div>

        <div style="height: 100%; width: 1px; background-color: grey; margin: 0 20px;"></div> <!-- Grey line separator -->

        <div style="flex: 1; padding-left: 10px;">
            <h2>Our Values</h2>
            <p>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        </div>

        <div style="flex: 1; padding-left: 10px;">
            <h2>Contact Information</h2>
            <p>Company Phone: 402-123-1234</p>
            <p>Company Email: nixiewander@gmail.com</p>
        </div>
    </div>

    <!-- Additional Content Sections as needed -->
{% endblock %}

website/templates/blog.html
{% extends 'website/base.html' %}

{% block content %}

    <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; padding: 20px;">
        <!-- Loop through each blog post and display -->
        {% for post in blog_posts %}
            <div class="blog-post" style="grid-row: span 2; box-sizing: border-box; border: 1px solid #ccc;">
                {% if post.photo %}
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" style="width: 100%; aspect-ratio: 1 / 1; object-fit: cover;">
                {% endif %}
                <div style="padding: 10px;">
                    <h2 style="margin-top: 0;">{{ post.title }}</h2>
                    <p>{{ post.content|truncatewords:30 }}</p>
                    <p style="color: darkgrey;">Posted by: {{ post.author.username }}</p>
                </div>
            </div>
        {% empty %}
            <p>No blog posts yet.</p>
        {% endfor %}
    </div>
{% endblock %}

website/templates/blog_create.html
<!DOCTYPE html>
<html lang="en">
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
    {% if perms.catalog.create_service %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit"/>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}

</html>

website/templates/index.html
{% extends 'website/base.html' %}
{% load static %}
{% block content %}

    <!-- Image Carousel START -->
    <div id="imageCarousel" class="carousel slide position-relative" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'images/image-1.jpg' %}" class="d-block w-100" alt="Image 1">
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/image-2.jpg' %}" class="d-block w-100" alt="Image 2">
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/image-3.jpg' %}" class="d-block w-100" alt="Image 2">
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/image-4.jpg' %}" class="d-block w-100" alt="Image 2">
            </div>
            <!-- Add more carousel items as needed -->
        </div>

        <div class="overlay"></div>
        <div class="text-center text-white position-absolute top-50 start-50 translate-middle">
            <h1 class="display-4">CS Landscaping Company</h1>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#imageCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#imageCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <!-- Image Carousel END -->

    <!-- ABOUT Section -->
    <div class="container-fluid mt-5">
        <div class="row d-flex align-items-center">
            <div class="col-md-6 text-left p-4">
                <h2>About the Company</h2>
                <p class="text-justify">
                    Welcome to CS Landscaping, where nature meets artistry. At CS Landscaping,
                    we are passionate about transforming outdoor spaces into lush, vibrant havens that
                    harmonize with the natural beauty of the environment. With a commitment to excellence,
                    our expert team of landscape architects and horticulturists collaborates closely with clients
                    to bring their vision to life.
                </p>
            </div>
            <div class="col-md-6 p-5">
                <img src="{% static 'images/image-4.jpg' %}" class="img-fluid" alt="Company Image">
            </div>
        </div>
    </div>

    <!-- REVIEWS Card Section -->
   <div class="container-fluid mt-5">
   <h2 class="text-center">Reviews</h2>
    <div class="row">
        {% for review in reviews %}
            <div class="col-md-3 mb-4">
                <div class="card border-0">
                    {% if review.review_image %}
                        <img src="{{ review.review_image.url }}" alt="Review Image" class="card-img-top rounded-top">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ review.review_rating }}/5 Stars</h5>
                        <p class="card-text">{{ review.review_comments }}</p>
                        <a href="{{ review.service_id.get_absolute_url }}" class="btn btn-primary">{{ review.service_id }}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

website/templates/website/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}CS Lawn Care{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #2A3C24">
    <a class="navbar-brand mb-0 h1" href="{% url 'contact_us' %}">CS Lawn Care</a>
    <button class="navbar-toggler" type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about_us' %}">About Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'service_list' %}">Services</a>
            </li>
            {% if user.is_superuser %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Admin Functions
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'service_create' %}">Add Service</a></li>
                            <li><a class="dropdown-item" href="{% url 'blog_create' %}">Add Blog Post</a></li>
                        </ul>
                    </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog' %}">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'review_create' %}">Write a Review</a>
            </li>
        </ul>
    </div>
 <ul class="nav navbar-nav ml-auto">
 {% if user.is_authenticated %}
 <li><a class="nav-link" href="{% url 'logout' %}"><span
class="glyphicon glyphicon-log-in"></span>Logout</a>
 </li>
 {% else %}
 <li><a class="nav-link" href="{% url 'login' %}"><span
class="glyphicon glyphicon-log-in"></span>Login</a>
 </li>
     <li><a class="nav-link" href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span>Sign Up</a>
     </li>

 {% endif %}
 </ul>
</nav>

{% block content %}
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>
</html>

website/templates/website/contact.html
<!DOCTYPE html>
<html lang="en">
{% extends "website/base.html" %}
<head>
    <meta charset="UTF-8">
    <title>Contact Info</title>
</head>
<body>
<p>Email: nixiewander@gmail.com</p>
<p>Phone Number: 402-608-0412</p>

</body>
</html>

website/templates/website/request_form.html
<!DOCTYPE html>
<html lang="en">
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
    {% if perms.website.add_review %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit"/>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}

</html>

website/templates/website/review_form.html
<!DOCTYPE html>
<html lang="en">
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
    {% if perms.website.add_review %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit"/>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}

</html>

website/templates/website/service_detail.html
{% extends "website/base.html" %}
{% block content %}
<h1>{{ service.service_title }}</h1>
    <p>Service Information: {{ service.service_info }}</p>
    <p>Cost of Service: {{ service.service_cost }}</p>
    {% if service.service_img %}
        <img src="{{ service.service_img.url }}" class="img-fixed"
             alt="{{ service.service_title }}">
    {% endif %}
{% endblock %}

website/templates/website/service_form.html
<!DOCTYPE html>
<html lang="en">
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
    {% if perms.catalog.create_service %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit"/>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}

</html>

website/templates/website/service_list.html
{% extends "website/base.html" %}
{% block content %}
    <div class="text-center">
        <h1>Services</h1>
    </div>
    {% if service_list %}
        <div class="row container-fluid p-5">
            {% for service in service_list %}
                <div class="col-md-4">
                    <div class="service-item text-center">
                        {% if service.service_img %}
                            <div class="image-container">
                            <!-- TODO: Change image dimensions to a square -->
                                <img src="{{ service.service_img.url }}" class="img-fixed"
                                     alt="{{ service.service_title }}">
                            </div>
                        {% endif %}
                        <h4 class="service-title">{{ service.service_title }}</h4>
                        <a href="{{ service.get_absolute_url }}" class="btn btn-primary">Learn More</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>There are no services</p>
    {% endif %}
{% endblock %}